"","instance_id","link","text","Fail to detect ambiguities/contradictions","Misalignment between internal thoughts and response message","Claiming that a task is done while it is not true.","Ignoring good suggestions from other agent","Not exploring every option proposed by other agents","Discontinued reasoning","Withholding relevant information","Derailing from task objectives","No attempt to verify outcome","Trajectory restart","Step repetition","Invented content","Blurring role"
"0","pydata__xarray-4493","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/pydata__xarray-4493_human.json","It seems that the original solution doesn't solve the issue. So it is a hard problem. In the final part the planner says that more tests are required but then it states that they have solved the problem. ","yes","no","no","no","no","no","no","no","no","no","no","no","no"
"1","matplotlib__matplotlib-25433","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/matplotlib__matplotlib-25433_human.json","The Navigator thinks also about possible solutions but then it does not communicate it to the Planner. At certain point the Executor states 'The above output is just an example' but the Planner thinks that the test are passed 'Thank you for running the test and providing the results'. ","yes","no","no","no","no","no","yes","no","no","no","no","no","yes"
"2","matplotlib__matplotlib-18869","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/matplotlib__matplotlib-18869_human.json","The trajectory ended with Planner asking to run some tests but no response from Executor.","no","no","no","no","no","no","no","no","yes","no","no","no","no"
"3","pallets__flask-5063","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/pallets__flask-5063_human.json","This is a feature request. The navigator proposed a solution for FastAPI and not for Flask. Multiple repeated imports. ","no","no","no","no","no","no","no","yes","no","yes","no","yes","no"
"4","astropy__astropy-12907","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/astropy__astropy-12907_human.json","The navigator continues proposing to edit _separable at the beginning. Then they located correctly _cstack. At certain point, it is proposed to check _coord_matrix but Navigator failed to propose its content. Instead, it proposed to pip install the package and open the file from the installed package. It also proposed a invented snippet that might be similator to the _coord_matrix function. ","no","no","no","no","no","no","no","no","no","yes","yes","yes","no"
"5","matplotlib__matplotlib-24265","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/matplotlib__matplotlib-24265_human.json","They have implemented an alternative solution. ","no","no","no","no","no","no","no","no","no","no","no","no","no"
"6","django__django-10924","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/django__django-10924_human.json","They located the wrong file to modify. No tests are run to verify. ","no","no","no","no","no","no","no","no","yes","no","no","no","no"
"7","scikit-learn__scikit-learn-10508","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/scikit-learn__scikit-learn-10508_human.json","They forgot the inverse_transform case.","no","no","no","no","no","no","no","no","no","no","no","no","no"
"8","pytest-dev__pytest-7168","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/pytest-dev__pytest-7168_human.json","They proposed another solution.","no","no","no","no","no","no","no","no","no","no","no","no","no"
"9","scikit-learn__scikit-learn-25570","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/scikit-learn__scikit-learn-25570_human.json","The example code provided at the beginning requires lighgbm. The agents decides to substitute this with a model inside scikit-learn. But the the Planner come back to lightgbm as it hasn't seen that the new code does not have it.  ","no","no","no","no","no","yes","no","no","no","no","no","no","no"
"10","sympy__sympy-11400","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/sympy__sympy-11400_human.json","The executor invented a conda activate command and asks explaination to Planner. Didn't run ccode(sinc(x)) at the end. ","no","no","no","no","no","no","no","no","yes","no","no","yes","no"
"11","django__django-11179","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/django__django-11179_human.json","Found the correct method to update, but failed to implement the patch.","no","no","no","no","no","no","no","no","yes","no","yes","no","no"
"12","sympy__sympy-12481","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/sympy__sympy-12481_human.json","The official solution does not make any sense. ","no","no","no","no","no","no","no","no","no","yes","no","no","no"
"13","astropy__astropy-14365","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/astropy__astropy-14365_human.json","The Nvigator has proposed a possible solution but it keeps it only for itself and doesn't communicate it to the Planner. The Planner found the point anyway. One solution is proposed and implemented but it doesn't work. Then, they wated to check the entire implementation, they started with the first lines, no modification is proposed, but suddenly they wanted to run the test again. During one of the iterations the Navigator returns the implementation of QDP with several repeated lines or repeated parameters. ","no","yes","no","no","no","no","yes","no","no","yes","yes","yes","yes"
"14","matplotlib__matplotlib-24334","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/matplotlib__matplotlib-24334_human.json","The Navigator internally proposes a solution but doesn't communicate it to the Planner. During one of the restarts, they focused on ticklabels instead of labels. ","no","no","no","no","no","no","yes","yes","no","yes","no","no","yes"
"15","mwaskom__seaborn-3407","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/mwaskom__seaborn-3407_human.json","No testing running at the end. ","no","no","no","no","no","no","no","no","yes","no","no","no","no"
"16","sphinx-doc__sphinx-8435","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/sphinx-doc__sphinx-8435_human.json","They evolved a lor around the correct file and method. ","no","no","no","no","no","no","no","no","yes","yes","no","no","no"
"17","astropy__astropy-7746","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/astropy__astropy-7746_human.json","It seems that at the beginning the editor modified a new file wcs_patched.py instead of wcs.py itself. The navigator forgot one case that need to be updated too. A very long trajectory to solve an easy problem. Hallucination from astropy.wcs import WCSWarningInfoWarningWarningWarningWarningWarningWarningWarningWarningWarningWarningWarningWarningWarningWarningWarningWarningWarningWarning","no","no","no","no","no","no","no","yes","no","yes","yes","yes","no"
"18","scikit-learn__scikit-learn-15535","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/scikit-learn__scikit-learn-15535_human.json","The localized the correct file but just are not able to find the correct lines to edit. From a certai point they started to deviate a little bit from the original issue. ","no","no","no","no","no","no","no","yes","no","no","no","no","no"
"19","pallets__flask-4992","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/pallets__flask-4992_human.json","Trajectory restart. The editor claimed an edit that was not made. ","no","no","yes","no","no","no","no","no","no","yes","no","no","no"
"20","psf__requests-1963","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/psf__requests-1963_human.json","It seems that they actually solved the problem.","no","no","no","no","no","no","no","no","no","yes","no","no","no"
"21","matplotlib__matplotlib-23563","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/matplotlib__matplotlib-23563_human.json","The Navigator internally proposes a solution without communicating it to the Planner. They didn't managed to replicate the issue described and started to unrelated steps to find something to edit. At the end the Planner decided to 'Wait for the user's response'. ","no","no","no","no","no","no","yes","yes","no","yes","yes","no","yes"
"22","mwaskom__seaborn-2848","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/mwaskom__seaborn-2848_human.json","They updated the user code instead of solving the issue in the repository. The navigator found different implementation of _lookup_single and talks about this fact to planner but planner doesn't take any steps to verifiy which one to use. Even if it is not a communication error, one agent talks about astropy in one round, probably it is in the system prompt. ","no","no","no","yes","no","no","no","yes","yes","yes","yes","yes","no"
"23","psf__requests-2317","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/psf__requests-2317_human.json","Actually, it seems that they found the solution, but they did not run the test. ","no","no","no","no","no","no","no","no","yes","no","no","no","no"
"24","astropy__astropy-6938","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/astropy__astropy-6938_human.json","The code navigator has located correctly the code snippet and proposed the correct patch, but while reporting the answer to the planner, instead of reporting the class FITS_rec, it reported FITS_record. This last class doesn't contain the code to be updated. From this point, the code navigator, based on wrong conclusions, continues to propose modifications to wrong classes and methods that are useless to solve the problem.","yes","no","no","no","no","no","no","no","no","yes","no","no","no"
"25","sphinx-doc__sphinx-11445","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/sphinx-doc__sphinx-11445_human.json","The executor internally states that it is ok, but then highlights the issue to the planner. ","yes","no","no","no","no","no","no","no","no","no","no","no","no"
"26","pylint-dev__pylint-6506","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/pylint-dev__pylint-6506_human.json","Initially, the navigator has already found the solution but it tells other things to planner. ","no","yes","no","no","no","no","no","no","no","no","no","no","no"
"27","scikit-learn__scikit-learn-13439","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/scikit-learn__scikit-learn-13439_human.json","For some reason, the patch resulted already implemented, but the agents passed to solve another problem. ","no","no","no","no","no","no","no","yes","no","no","no","no","no"
"28","django__django-11742","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/django__django-11742_human.json","They located the wrong file to update. ","no","no","no","no","no","no","no","no","yes","no","no","no","no"
"29","matplotlib__matplotlib-23299","https://github.com/LakshyAAAgrawal/MultiAgentFailureTaxonomyAnnotations/blob/main/HyperAgent/matplotlib__matplotlib-23299_human.json","They are convinced that an old pull request already solved the problem. They found out the correct file to update, but just cannot implement the correct patch. ","no","no","no","yes","no","yes","no","no","yes","yes","yes","no","no"
